# Generated by Django 3.0.5 on 2020-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproduct',
            name='mobile_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
