# Generated by Django 3.0.5 on 2020-04-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobileproduct_mobile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Askqa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(choices=[('price', 'ราคา'), ('shipping', 'ขนส่ง'), ('change', 'เปลี่ยนเครื่องใหม่')], default='price', max_length=100)),
                ('detail', models.TextField(null=True)),
            ],
        ),
    ]
